version: "3.8"

services:
  mailer-lib:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mailer-lib
    environment:
      - VIRTUAL_HOST=mailer.hexagn.in
      - VIRTUAL_PORT=3002
      - LETSENCRYPT_HOST=mailer.hexagn.in
      - LETSENCRYPT_EMAIL=jigar@hexagn.in
    networks:
      - proxy-net
      
networks:
  proxy-net:
    name: nginx-proxy
    external: true
